version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: trustpay-postgres
    environment:
      POSTGRES_DB: trustpay_dev
      POSTGRES_USER: trustpay
      POSTGRES_PASSWORD: trustpay123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: